repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: debug-statements
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.38.0
  hooks:
  - id: yamllint
    exclude: "^(.github/|action.yaml$)"
    args: [--format, parsable, --strict]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.10
  hooks:
  - id: ruff-check
  - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.12
  hooks:
  - id: uv-lock

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.12
  hooks:
    - id: actionlint

- repo: local
  hooks:
  - id: readme-update
    name: README update
    language: python
    entry: ./tools/generate_docs.py
    files: ^(README\.md|Pulumi\.yaml|tools/generate_docs\.py)$
    additional_dependencies:
    - pyyaml~=6.0.2
