name: "End to End Tests"

on:
  workflow_call:

permissions:
  id-token: write
  actions: read
  contents: read

jobs:
  test-spawn:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_MAIN_ACCOUNT_ID }}:role/scality-github-e2e-infrastructure
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: eu-north-1

      - name: Spawn platform
        uses: ./
        with:
          action: spawn
          artifacts_user: ${{ secrets.ARTIFACTS_USER }}
          artifacts_password: ${{ secrets.ARTIFACTS_PASSWORD }}
          stack_name: "${{ github.workflow }}-${{ github.run_number }}"
          configuration: |-
            instance_image: rocky-9

      - name: Test to ssh
        run: |-
          ssh -F ssh_config bastion hostname
          ssh -F ssh_config node-1 hostname
          ssh -F ssh_config node-2 hostname
          ssh -F ssh_config node-3 hostname

  destroy:
    needs: test-spawn
    runs-on: ubuntu-24.04
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_MAIN_ACCOUNT_ID }}:role/scality-github-e2e-infrastructure
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: eu-north-1

      - name: Destroy platform
        uses: ./
        with:
          action: destroy
          stack_name: "${{ github.workflow }}-${{ github.run_number }}"
