name: "Pre Merge"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

# One run per branch at a time. On push, cancels any ongoing run since nobody
# is waiting for it.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.13"

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run Pre-commit
        # NOTE: For now this action is not available in org
        # so let's do it manually
        #uses: pre-commit/action@v3.0.1
        shell: bash
        run: >-
          pip install pre-commit &&
          pre-commit run --show-diff-on-failure --color=always --all-files

  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yaml
    needs: lint
    secrets: inherit
